name: Gatsby Publish

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache-dependency-path: ./package.json
          cache: yarn

      - name: Get correct version of Yarn
        run: corepack enable; yarn set version berry

      # Having a cache can save us a lot of time when installing dependencies
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ./sites/devsite/public
            ./sites/devsite/.cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      # This is the yarn install step
      - name: Install dependencies
        working-directory: .
        run: yarn install --immutable --immutable-cache

      - name: Build with Gatsby
        working-directory: .
        env:
          PREFIX_PATHS: 'true'
        run: yarn run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./sites/devsite/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
